### ISSUE TITLE
Unable to get data in bag

### ISSUE THREAD

**Issue by CourchesneA** [gaia-platform/rosbag2_snapshot#6]
I am having trouble figuring how the time is supposed to work. I am trying a basic example, with default values.

I have a webcam streaming on topic `/camera_raw/compressed` that I know is publishing at 1fps.
The snapshot server is running with the following config file:

```
/**:
  ros__parameters:
    default_duration_limit: 15.0
    default_memory_limit: 1024.0 
```

and I take a snapshot with the CLI service call:
```
ros2 service call /trigger_snapshot rosbag2_snapshot_msgs/srv/TriggerSnapshot "{filename: 'logs/bag1', topics: [], start_time: {sec: 0, nanosec: 0}, stop_time: {sec: 0, nanosec: 0}}"
```

but no messages are logged into the bag: (bag1/metadata.yaml)
```
    - topic_metadata:
        name: /camera_raw/compressed
        type: sensor_msgs/msg/CompressedImage
        serialization_format: cdr 
        offered_qos_profiles: ""
      message_count: 0
```

I tried setting the end_time to max_int to make sure the messages were in the time window but it does not seem to change anything. What time format is expected ? Would it be possible to have some more examples commands ?
